// SPDX-License-Identifier: GPL-3.0-or-later

package cli

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/spf13/cobra"
)

// generatedHookMarker is the comment we embed in every hook this
// command writes. --uninstall checks for this marker before removing
// a file so a hand-written hook of the same name is never clobbered.
// Verbatim string — never reformat or i18n.
const generatedHookMarker = "Generated by `commitbrief install-hook`"

// supportedHooks lists the git hook names install-hook accepts.
// Deliberately limited to the three review-relevant points; other
// hooks (post-commit, post-receive, etc.) have no obvious
// commitbrief workflow and would just clutter the surface.
var supportedHooks = []string{"pre-commit", "commit-msg", "pre-push"}

func newInstallHookCmd() *cobra.Command {
	var hookName string
	var uninstall bool
	cmd := &cobra.Command{
		Use:   "install-hook",
		Short: "Install (or uninstall) a git hook that runs commitbrief on commit",
		Long: `Drops a small shell script at .git/hooks/<name> that runs:

    commitbrief --staged --fail-on=critical --quiet --no-cost-check

so every commit either passes review or is blocked by a critical-
severity finding. Default hook is pre-commit; --hook chooses
commit-msg or pre-push.

Existing hook files are refused unless --yes is passed; with --yes
the previous content is backed up to <name>.bak.<timestamp>.

--uninstall removes a hook we wrote (matched via embedded marker
comment). Refuses to touch a hook that doesn't carry our marker.`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			app, err := resolveContext(true)
			if err != nil {
				return err
			}
			if app.RepoRoot == "" {
				return errors.New(app.Catalog.T("install_hook.not_in_repo"))
			}
			if !isSupportedHook(hookName) {
				return errors.New(app.Catalog.T("install_hook.unsupported", hookName, strings.Join(supportedHooks, ", ")))
			}
			hookPath := filepath.Join(app.RepoRoot, ".git", "hooks", hookName)
			if uninstall {
				return runUninstallHook(cmd, app, hookPath)
			}
			return runInstallHook(cmd, app, hookPath)
		},
	}
	cmd.Flags().StringVar(&hookName, "hook", "pre-commit", "git hook name (pre-commit | commit-msg | pre-push)")
	cmd.Flags().BoolVar(&uninstall, "uninstall", false, "remove a previously installed hook (only one this command wrote)")
	return cmd
}

func isSupportedHook(name string) bool {
	for _, h := range supportedHooks {
		if h == name {
			return true
		}
	}
	return false
}

// hookScript returns the shell content written to .git/hooks/<name>.
// The marker comment is the load-bearing part — uninstall relies on
// matching it verbatim. The exec'd command line mirrors the README
// "install-hook" example so users tweaking flags can find the source.
func hookScript() string {
	return fmt.Sprintf(`#!/usr/bin/env sh
# %s — do not edit.
# Re-run 'commitbrief install-hook' to regenerate, or pass --uninstall to remove.
exec commitbrief --staged --fail-on=critical --quiet --no-cost-check
`, generatedHookMarker)
}

// runInstallHook writes the hook file with 0755 mode. If a hook
// already lives at the target path it refuses unless --yes is in
// effect, in which case the existing content is moved to a
// timestamped .bak file so a misfire never destroys a user-curated
// hook silently.
func runInstallHook(cmd *cobra.Command, app *appContext, hookPath string) error {
	if _, err := os.Stat(hookPath); err == nil {
		if !global.yes {
			return errors.New(app.Catalog.T("install_hook.exists", hookPath))
		}
		ts := time.Now().UTC().Format("20060102T150405Z")
		backup := hookPath + ".bak." + ts
		if err := os.Rename(hookPath, backup); err != nil {
			return fmt.Errorf("install-hook: back up %s: %w", hookPath, err)
		}
		_, _ = fmt.Fprintln(cmd.OutOrStdout(), app.Catalog.T("install_hook.backed_up", backup))
	} else if !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("install-hook: stat %s: %w", hookPath, err)
	}

	if err := os.MkdirAll(filepath.Dir(hookPath), 0o755); err != nil {
		return fmt.Errorf("install-hook: mkdir hooks dir: %w", err)
	}
	if err := os.WriteFile(hookPath, []byte(hookScript()), 0o755); err != nil {
		return fmt.Errorf("install-hook: write %s: %w", hookPath, err)
	}
	_, _ = fmt.Fprintln(cmd.OutOrStdout(), app.Catalog.T("install_hook.success", hookPath))
	return nil
}

// runUninstallHook removes the hook only if it carries our marker
// comment. Missing file is treated as success ("already not
// installed") so the command is idempotent on the no-op side.
func runUninstallHook(cmd *cobra.Command, app *appContext, hookPath string) error {
	data, err := os.ReadFile(hookPath)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			_, _ = fmt.Fprintln(cmd.OutOrStdout(), app.Catalog.T("install_hook.not_installed", hookPath))
			return nil
		}
		return fmt.Errorf("install-hook: read %s: %w", hookPath, err)
	}
	if !strings.Contains(string(data), generatedHookMarker) {
		return errors.New(app.Catalog.T("install_hook.foreign", hookPath))
	}
	if err := os.Remove(hookPath); err != nil {
		return fmt.Errorf("install-hook: remove %s: %w", hookPath, err)
	}
	_, _ = fmt.Fprintln(cmd.OutOrStdout(), app.Catalog.T("install_hook.uninstalled", hookPath))
	return nil
}
