// SPDX-License-Identifier: GPL-3.0-or-later

package cli

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/spf13/cobra"
)

// generatedHookMarker is the comment we embed in every hook this
// command writes. --uninstall checks for this marker before removing
// a file so a hand-written hook of the same name is never clobbered.
// Verbatim string — never reformat or i18n.
const generatedHookMarker = "Generated by `commitbrief install-hook`"

// supportedHooks lists the git hook names install-hook accepts.
// Deliberately limited to the three review-relevant points; other
// hooks (post-commit, post-receive, etc.) have no obvious
// commitbrief workflow and would just clutter the surface.
var supportedHooks = []string{"pre-commit", "commit-msg", "pre-push"}

func newInstallHookCmd() *cobra.Command {
	var hookName string
	var uninstall bool
	cmd := &cobra.Command{
		Use:   "install-hook",
		Short: "Install (or uninstall) a git hook that runs commitbrief on commit",
		Long: `Drops a small shell script at .git/hooks/<name>.

For pre-commit (default) and commit-msg the body runs:

    commitbrief --staged --fail-on=critical --quiet --no-cost-check

so every commit either passes review or is blocked by a critical-
severity finding.

For pre-push the body parses git's per-ref stdin protocol and runs
'commitbrief diff <remote>..<local>' for each ref being pushed,
exiting non-zero on the first critical finding to block the push.

Existing hook files are refused unless --yes is passed; with --yes
the previous content is backed up to <name>.bak.<timestamp>.

--uninstall removes a hook we wrote (matched via embedded marker
comment). Refuses to touch a hook that doesn't carry our marker.`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			app, err := resolveContext(true)
			if err != nil {
				return err
			}
			if app.RepoRoot == "" {
				return errors.New(app.Catalog.T("install_hook.not_in_repo"))
			}
			if !isSupportedHook(hookName) {
				return errors.New(app.Catalog.T("install_hook.unsupported", hookName, strings.Join(supportedHooks, ", ")))
			}
			hookPath := filepath.Join(app.RepoRoot, ".git", "hooks", hookName)
			if uninstall {
				return runUninstallHook(cmd, app, hookPath)
			}
			return runInstallHook(cmd, app, hookPath)
		},
	}
	cmd.Flags().StringVar(&hookName, "hook", "pre-commit", "git hook name (pre-commit | commit-msg | pre-push)")
	cmd.Flags().BoolVar(&uninstall, "uninstall", false, "remove a previously installed hook (only one this command wrote)")
	return cmd
}

func isSupportedHook(name string) bool {
	for _, h := range supportedHooks {
		if h == name {
			return true
		}
	}
	return false
}

// hookScript returns the shell content written to .git/hooks/<name>.
// The marker comment is the load-bearing part — uninstall relies on
// matching it verbatim across every hook variant.
//
// pre-commit / commit-msg share the same body: review the staged tree
// before the commit is finalised, fail the commit on a critical-or-
// worse finding. pre-push is different: git invokes it with the
// remote + URL as positional args and feeds a "<local-ref> <local-sha>
// <remote-ref> <remote-sha>" line per ref on stdin (see githooks(5)).
// We loop over those refs and review the actual range being pushed via
// `commitbrief diff`, so the developer is screened on *what they're
// shipping*, not the current index. Branch deletions (local-sha is
// all zeros) are skipped because there is no diff to review.
//
// UC-04 in PATCH_ROADMAP: prior to v0.9.1 every hook variant got the
// same `--staged` body, which silently no-op'd at push time when the
// index was already clean and meant pre-push never actually screened
// outgoing commits.
func hookScript(name string) string {
	if name == "pre-push" {
		// $z40 is the 40-zero hex string git uses to mean "no such ref"
		// (deletion on the local side; new branch on the remote side).
		// Quoting matters: each var must be quoted so an empty value
		// doesn't merge fields. `read` exits non-zero on EOF, which is
		// the normal end-of-stream signal — `|| break` lets us drain the
		// loop cleanly without -e tripping.
		return fmt.Sprintf(`#!/usr/bin/env sh
# %s — do not edit.
# Re-run 'commitbrief install-hook --hook=pre-push' to regenerate, or pass --uninstall to remove.
#
# Pre-push contract (githooks(5)): one line per ref on stdin, format
# "<local-ref> <local-sha> <remote-ref> <remote-sha>". A 40-zero sha
# on the local side means the branch is being deleted (nothing to
# review); a 40-zero sha on the remote side means the branch is new
# (review the tip commit). Otherwise review the inclusive range
# remote-sha..local-sha.
set -eu

z40="0000000000000000000000000000000000000000"
while read -r local_ref local_sha remote_ref remote_sha || [ -n "${local_ref-}" ]; do
    if [ "${local_sha}" = "${z40}" ]; then
        continue
    fi
    if [ "${remote_sha}" = "${z40}" ]; then
        range="${local_sha}"
    else
        range="${remote_sha}..${local_sha}"
    fi
    if ! commitbrief diff "${range}" --fail-on=critical --quiet --no-cost-check; then
        exit 1
    fi
done

exit 0
`, generatedHookMarker)
	}
	return fmt.Sprintf(`#!/usr/bin/env sh
# %s — do not edit.
# Re-run 'commitbrief install-hook' to regenerate, or pass --uninstall to remove.
exec commitbrief --staged --fail-on=critical --quiet --no-cost-check
`, generatedHookMarker)
}

// runInstallHook writes the hook file with 0755 mode. If a hook
// already lives at the target path it refuses unless --yes is in
// effect, in which case the existing content is moved to a
// timestamped .bak file so a misfire never destroys a user-curated
// hook silently.
func runInstallHook(cmd *cobra.Command, app *appContext, hookPath string) error {
	if _, err := os.Stat(hookPath); err == nil {
		if !global.yes {
			return errors.New(app.Catalog.T("install_hook.exists", hookPath))
		}
		ts := time.Now().UTC().Format("20060102T150405Z")
		backup := hookPath + ".bak." + ts
		if err := os.Rename(hookPath, backup); err != nil {
			return fmt.Errorf("install-hook: back up %s: %w", hookPath, err)
		}
		_, _ = fmt.Fprintln(cmd.OutOrStdout(), app.Catalog.T("install_hook.backed_up", backup))
	} else if !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("install-hook: stat %s: %w", hookPath, err)
	}

	if err := os.MkdirAll(filepath.Dir(hookPath), 0o755); err != nil {
		return fmt.Errorf("install-hook: mkdir hooks dir: %w", err)
	}
	if err := os.WriteFile(hookPath, []byte(hookScript(filepath.Base(hookPath))), 0o755); err != nil {
		return fmt.Errorf("install-hook: write %s: %w", hookPath, err)
	}
	_, _ = fmt.Fprintln(cmd.OutOrStdout(), app.Catalog.T("install_hook.success", hookPath))
	return nil
}

// runUninstallHook removes the hook only if it carries our marker
// comment. Missing file is treated as success ("already not
// installed") so the command is idempotent on the no-op side.
func runUninstallHook(cmd *cobra.Command, app *appContext, hookPath string) error {
	data, err := os.ReadFile(hookPath)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			_, _ = fmt.Fprintln(cmd.OutOrStdout(), app.Catalog.T("install_hook.not_installed", hookPath))
			return nil
		}
		return fmt.Errorf("install-hook: read %s: %w", hookPath, err)
	}
	if !strings.Contains(string(data), generatedHookMarker) {
		return errors.New(app.Catalog.T("install_hook.foreign", hookPath))
	}
	if err := os.Remove(hookPath); err != nil {
		return fmt.Errorf("install-hook: remove %s: %w", hookPath, err)
	}
	_, _ = fmt.Fprintln(cmd.OutOrStdout(), app.Catalog.T("install_hook.uninstalled", hookPath))
	return nil
}
